"""initial_schema

Revision ID: 307c95ecdb87
Revises: 
Create Date: 2026-03-26 21:58:34.976880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '307c95ecdb87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_categories_parent_id', table_name='categories')
    op.drop_index('idx_categories_slug', table_name='categories')
    op.drop_constraint('newsletter_subscribers_email_key', 'newsletter_subscribers', type_='unique')
    op.create_index(op.f('ix_newsletter_subscribers_email'), 'newsletter_subscribers', ['email'], unique=True)
    op.drop_index('idx_order_items_order_id', table_name='order_items')
    op.drop_index('idx_order_items_product_id', table_name='order_items')
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('idx_orders_created_at', table_name='orders')
    op.drop_index('idx_orders_order_number', table_name='orders')
    op.drop_index('idx_orders_payment_status', table_name='orders')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_user_id', table_name='orders')
    op.drop_constraint('orders_order_number_key', 'orders', type_='unique')
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_delivered_at'), 'orders', ['delivered_at'], unique=False)
    op.create_index(op.f('ix_orders_guest_email'), 'orders', ['guest_email'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    op.create_index(op.f('ix_orders_shipped_at'), 'orders', ['shipped_at'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.drop_index('idx_products_created_at', table_name='products')
    op.drop_index('idx_products_is_active', table_name='products')
    op.drop_index('idx_products_is_featured', table_name='products')
    op.drop_index('idx_products_price', table_name='products')
    op.drop_index('idx_products_rating', table_name='products')
    op.drop_index('idx_products_slug', table_name='products')
    op.drop_index('idx_products_sold_count', table_name='products')
    op.drop_constraint('products_sku_key', 'products', type_='unique')
    op.drop_constraint('products_slug_key', 'products', type_='unique')
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_is_featured'), 'products', ['is_featured'], unique=False)
    op.create_index(op.f('ix_products_is_on_sale'), 'products', ['is_on_sale'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_price'), 'products', ['price'], unique=False)
    op.create_index(op.f('ix_products_rating'), 'products', ['rating'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_index(op.f('ix_products_sold_count'), 'products', ['sold_count'], unique=False)
    op.alter_column('referrals', 'referrer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.alter_column('referrals', 'referrer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_products_sold_count'), table_name='products')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_rating'), table_name='products')
    op.drop_index(op.f('ix_products_price'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_is_on_sale'), table_name='products')
    op.drop_index(op.f('ix_products_is_featured'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.create_unique_constraint('products_slug_key', 'products', ['slug'])
    op.create_unique_constraint('products_sku_key', 'products', ['sku'])
    op.create_index('idx_products_sold_count', 'products', ['sold_count'], unique=False)
    op.create_index('idx_products_slug', 'products', ['slug'], unique=False)
    op.create_index('idx_products_rating', 'products', ['rating'], unique=False)
    op.create_index('idx_products_price', 'products', ['price'], unique=False)
    op.create_index('idx_products_is_featured', 'products', ['is_featured'], unique=False)
    op.create_index('idx_products_is_active', 'products', ['is_active'], unique=False)
    op.create_index('idx_products_created_at', 'products', ['created_at'], unique=False)
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_shipped_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_guest_email'), table_name='orders')
    op.drop_index(op.f('ix_orders_delivered_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.create_unique_constraint('orders_order_number_key', 'orders', ['order_number'])
    op.create_index('idx_orders_user_id', 'orders', ['user_id'], unique=False)
    op.create_index('idx_orders_status', 'orders', ['status'], unique=False)
    op.create_index('idx_orders_payment_status', 'orders', ['payment_status'], unique=False)
    op.create_index('idx_orders_order_number', 'orders', ['order_number'], unique=False)
    op.create_index('idx_orders_created_at', 'orders', ['created_at'], unique=False)
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_order_items_product_id', 'order_items', ['product_id'], unique=False)
    op.create_index('idx_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.drop_index(op.f('ix_newsletter_subscribers_email'), table_name='newsletter_subscribers')
    op.create_unique_constraint('newsletter_subscribers_email_key', 'newsletter_subscribers', ['email'])
    op.create_index('idx_categories_slug', 'categories', ['slug'], unique=False)
    op.create_index('idx_categories_parent_id', 'categories', ['parent_id'], unique=False)
    # ### end Alembic commands ###
