name: Auto Assign PRs

on:
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/auto-assign-action@v1.2.4
        with:
          configuration-path: .github/auto_assign.yml
